import uuid from 'react-uuid';

import itemImg from 'images/dynamic/item-one.jpg';
import adidasSmall from 'images/dynamic/adidas-small.png';
import adidasBig from 'images/dynamic/adidas-big.png';

export const dummyProductsData = [
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
  {
    name: 'Adidas Ultimashow Indigo BackPack',
    price: 1629,
    priceText: '1,629',
    productImage: itemImg,
    brandImage: adidasBig,
    brandSmallImage: adidasSmall,
    brandName: 'Adidas',
    currency: 'EGP',
    id: uuid(),
  },
];
